spring.application.name=interviewhub-ai

# server.port=8081
server.port=${PORT:8081}
# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Swagger UI Path (we'll configure Swagger later)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

file.upload-dir=uploads

springdoc.swagger-ui.persistAuthorization=true

# ==========================
# Gemini API
# ==========================


gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}